### ISSUE TITLE
[question] Cursor question

### ISSUE THREAD

**Issue by canonic-epicure** [MScholtes/VirtualDesktop#1]
Hi,

Will every desktop, created by your utility, be having a separate cursor / focus management (similar to xvfb)?

Or, lets say, if a text field in desktop1 receives focus then focus will be gone from the desktop2?

I'd like to use this utility to run several Selenium tests in parallel, but "focus fighting" is problem that prevents it.

Thank you, Nickolay

**Comment by MScholtes** [comment]
Hello Nickolay,

sorry for the late answer, I have been to hospital for a while.

I guess what you're trying to do will not work. Virtual desktops are a feature of Windows 10 (and not my tool), but there is only one message queue. When you try to automate tests, you only have access to the windows on the active desktop.

Greetings

Markus

**Comment by SamuraiJack** [comment]
Ok, I guess I'll have to experiment.. Thanks and feel better!
