### ISSUE TITLE
[ANN] Videfix

### ISSUE THREAD

**Issue by LinqLover** [MScholtes/VirtualDesktop#11]
Hi @MScholtes, thank you again for this helpful project! I just wanted to inform you or any other person who might matter that I just published **[Videfix](https://github.com/LinqLover/Videfix)**, which uses your API in a small GUI to save and restore window arrangements automatically. I needed to [copy and rearrange](https://github.com/LinqLover/Videfix/tree/master/MScholtes.VirtualDesktop) the source files as your repo is not really implemented as a library, please feel absolutely free to copy back the rearrangement as you would like to do. Hope you like it!

Sorry for spamming your issues, you can safely close this issue at any time. :-)

**Comment by MScholtes** [comment]
Hello @LinqLover, thank you very much for referring and using my source code. I wish much fun and good luck with your interesting project.

Greetings
Markus
