### ISSUE TITLE
Question: is it possible to name new virtual desktops?

### ISSUE THREAD

**Issue by thatsIch** [MScholtes/VirtualDesktop#12]
When you create a new desktop they are always called "Desktop 1", "Desktop 2", etc.

I wonder if the API supports naming them?

**Comment by MScholtes** [comment]
Released Windows 10 versions do not support naming of virtual desktops.

Windows 10 20H1 will support naming of virtual desktops, but I do not know if there is an API or if Microsoft will publish the API definitions.

Greetings

Markus
