### ISSUE TITLE
Feature Request: Cycle/wrap to next right/left desktop

### ISSUE THREAD

**Issue by cb109** [MScholtes/VirtualDesktop#14]
Foremost: Love it, almost exactly what I needed, thanks for sharing!

I wanted to have a commandline tool that I can bind to some other hot-corner GUI to quickly switch between virtual desktops. I was able to build it by wrapping yours: https://gist.github.com/cb109/7d3d4ad6d3a3267ac0e1ced64cc9982e#file-cycle_virtual_desktops-py-L45-L56

Since your tool is focused on virtual desktops and moving/switching already it would be nice to have that feature included, I'm certain there are other people that would be happy abut it as well.

Cheers!

**Comment by MScholtes** [comment]
Why don't you use the parameters /Left and /Right?

Greetings

Markus

**Comment by cb109** [comment]
@MScholtes Good suggestion, thanks! No idea how I didn't see those... Do you see a possibility to create this "wrapping around" behaviour with the existing commandline options once we reach the left or right "edge" of the desktops?

**Comment by LinqLover** [comment]
@cb109 If I understand you correctly, your concern is not related to this repo and it's API at all :) For the API, `/Left` and `/Right` should definitely be the right protocol. What's wrong with winxcorners which you appear to try to use?

**Comment by cb109** [comment]
@LinqLover I think there is a misunderstanding and I am sorry I did not make my intention more clear from the start. There is nothing wrong with WinXCorners, my approach gives me the result I want, I just thought it may be nice to get that from VirtualDesktop directly, let me explain.

As far as I understand, `/Left` and `/Right` will switch to the corresponding desktop, as long as there is one based on the current position. When I am at the rightmost desktop already, calling `/Right` will error out, as there is no other desktop to our right.

```
Step 1  +----------------+   +----------------+
        |                |   |                |
        | 0              |   | 1              |
        |                |   |                |
        | we are here    |   |                |
        +----------------+   +----------------+

        /Right +------------>



Step 2  +----------------+   +----------------+
        |                |   |                |
        | 0              |   | 1              |
        |                |   |                |
        |                |   | we are here    |
        +----------------+   +----------------+

                             /Right +------------> Error!

```

I would instead like it to "wrap around" so we end up at the leftmost desktop again. So basically calling `/Right` or `/Left` any number of times in succession would never fail, just cycle through desktops in a loop.

I was under the impression that maybe I could chain the existing API commands in a way that allows for this behaviour, but it's probably impossible. Adding a new `/Wrap` or `/Loop` or `/Torus` argument could allow for that, or changing the default behaviour of `/Left` and `/Right`.

Of course, this is all just a humble suggestion 🤗

**Comment by LinqLover** [comment]
Ah, now I see. This concept is not propagated by Microsoft, but I don't see a reason not to introduce it. I would propose to name it `/CycleLeft` and `/CycleRight`, for example.

(However, this repo is basically just a big gist ... If other people use it, it would be really useful to separate library and examples. See my efforts in [Videfix](https://github.com/LinqLover/Videfix/tree/master/MScholtes.VirtualDesktop) how I solved it.)

**Comment by MScholtes** [comment]
Hello cb109,

I made the changes you wish in the new version 1.4.4. In order not to break any existing scripts I added two parameters **/Wrap** and **/NoWrap**:
**/Wrap** changes to wrapping mode (the mode you wish)
**/NoWrap** changes back to the old mode (generates an error on "looking over the edge"). This is the default mode.

For example you can use:
**_virtualdesktop /Wrap /left_**
now for your needs.

@LinqLover: Virtualdesktop is neither a library nor a gist, it is a standalone tool.

Greetings

Markus

**Comment by LinqLover** [comment]
Great to hear this!

@MScholtes I know it is organized as a tool, I was only talking about its internal modularity. You put all the code that could serve as an independent library into the same class as the CLI logic. In terms of reusability, this is kind of waste of all the time you appear to have spent on working out the ComImports and designing the architecture. However, this is only a kind hint :-)

**Comment by cb109** [comment]
@MScholtes Thanks, I do appreciate that! Can confirm it works like a charm :+1:

**Comment by MScholtes** [comment]
You're welcome
