### ISSUE TITLE
Switch desktop transition effect

### ISSUE THREAD

**Issue by Vodkaneat** [MScholtes/VirtualDesktop#16]
A small thing, I'm running Win 10 1909, when I switch desktops using the default shortcut keys (i.e. CTRL+WIN+RIGHT), there is a transition effect; the windows will slide to the next desktop.

When I use /Left or /Right this transition effect is missing, it would be nice if the behaviour was the same as the shortcut keys.

**Comment by MScholtes** [comment]
Hello Vodkaneat,

I' sorry to say that Microsoft did not expose this animation in the COM API for virtual Desktops. There is no way to implement this feature but to program it completely new. The expense does not justify the use, so I will not fulfill the request.

Greetings

Markus

**Comment by Vodkaneat** [comment]
Understood, thanks for your response, and for the Project :)
