### ISSUE TITLE
Feature request: Action by title?

### ISSUE THREAD

**Issue by bilogic** [MScholtes/VirtualDesktop#17]
Hi,

No hurry for this.
I'm trying to move virtual boxes individually, i.e. pin/unpin etc but could not as they share the same application name. Using title could be one possibility, perhaps a titles that contain the "search term" option.

Thank you.

**Comment by MScholtes** [comment]
Hello bilogic,

I will have a look at this. I'm not sure if there is an easy or satisfying solution for your request as there are main and child windows and the own windows might have to be filtered out.

Greetings

Markus

**Comment by MScholtes** [comment]
Hello bilogic,

I uploaded the new version 1.5 of Virtualdesktop today. There is an extended parameter **/MoveWindowHandle** and new parameters **/GetDesktopFromWindowHandle, /IsWindowHandleOnDesktop, /PinWindowHandle, /UnPinWindowHandle** and **/IsWindowHandlePinned**. All of them accept a string that is searched in the titles of the desktop windows (case insensitive). On the first window that fits the action will be taken.

I hope that's what you need.

Greetings

Markus

**Comment by bilogic** [comment]
PERFECT! THANKS!

**Comment by bilogic** [comment]
Pardon me, an idea just came up as I'm trying to move all Chrome windows to my current desktop, how about having another pipeline parameter to act on all matching windows instead of 1? It is ok if it is not pipeline, ```VirtualDesktop.exe``` can be executed multiple times to get the same effect. Thank you.
