### ISSUE TITLE
Move active window to desktop

### ISSUE THREAD

**Issue by avionbg** [MScholtes/VirtualDesktop#2]
Hi there, this is really great tool that fills missing features in win 10. One thing that you could add is option to move active window to any desktop. I've implemented that by adding following code and command option (Based on your moveWindow method) :

		[DllImport("user32.dll")]
		static extern IntPtr GetForegroundWindow();
		public void MoveActive()
		{
			IntPtr hWnd = GetForegroundWindow();
			int processId;
			if (hWnd == IntPtr.Zero) throw new ArgumentNullException();
			GetWindowThreadProcessId(hWnd, out processId);

			if (System.Diagnostics.Process.GetCurrentProcess().Id == processId)
			{ // window of process
				try // the easy way (if we are owner)
				{
					DesktopManager.VirtualDesktopManager.MoveWindowToDesktop(hWnd, ivd.GetId());
				}
				catch // window of process, but we are not the owner
				{
					IApplicationView view;
					DesktopManager.ApplicationViewCollection.GetViewForHwnd(hWnd, out view);
					DesktopManager.VirtualDesktopManagerInternal.MoveViewToDesktop(view, ivd);
				}
			}
			else
			{ // window of other process
				IApplicationView view;
				DesktopManager.ApplicationViewCollection.GetViewForHwnd(hWnd, out view);
				DesktopManager.VirtualDesktopManagerInternal.MoveViewToDesktop(view, ivd);
			}
		}

**Comment by MScholtes** [comment]
Hello avionbg,

I'm sorry, it took some time :-) 
I added the new option MoveActiveWindow today!

Thank you very much

Markus
