### ISSUE TITLE
Can't run on Windows  Version 10.0.21327.1000+

### ISSUE THREAD

**Issue by Herman-Wu** [MScholtes/VirtualDesktop#22]
I got the following error when tried to run on  Windows  Version 10.0.21327.1000+

Unhandled Exception: System.TypeInitializationException: The type initializer for 'VirtualDesktop.DesktopManager' threw an exception. ---> System.InvalidCastException: Specified cast is not valid.
   at VirtualDesktop.IServiceProvider10.QueryService(Guid& service, Guid& riid)
   at VirtualDesktop.DesktopManager..cctor()
   --- End of inner exception stack trace ---
   at VDeskTool.Program.Main(String[] args)

**Comment by MScholtes** [comment]
Hello Herman-Wu,

Microsoft has changed the API for virtual desktops again with the insider edition.

I do not have access to an insider edition so I have to wait for the release version to fix this (Microsoft will probably change the settings one more time).

Sorry for that

Markus

**Comment by MScholtes** [comment]
Closed since no reaction for over 4 weeks

**Comment by NyaMisty** [comment]
Please don't close issues like this simply because of inactivity.
There's plenty of sources:
1. https://github.com/Grabacr07/VirtualDesktop
2. https://gitmemory.com/wil70

**Comment by NyaMisty** [comment]
See #25
