### ISSUE TITLE
When switching desktop the windows try to gain focus and flashes on the taskbar until i click on them

### ISSUE THREAD

**Issue by bugwheels94** [MScholtes/VirtualDesktop#23]

**Comment by MScholtes** [comment]
Hello bugwheels94,

I think this is the expected behaviour. When a program wants to notify you that it wants to be activated its icon flashes and turns orange. **VirtualDesktop** does not care about Window activation.

As far as I know you can change that behaviour in _Control Panel_ or with a registry hack.

Greetings

Markus

**Comment by bugwheels94** [comment]
Hi Markus,

I used to use AHK using dlls for this think till yesterday but that was super messy and unreliable. I have now set up this repo inside AHK and it works but I am not able to understand why all applications like VSCode editor or Browser want focus when using this repo and not AHK Dlls.

**Comment by bugwheels94** [comment]
Regedit hack indeed worked. I did not set it to 0 by mistake. You have no idea how much simpler your software has made my life. desktop switching just gives the feel of linux/mac now. Truly appreciate your work

**Comment by shellwhale** [comment]
I am having this very issue, this is extremely annoying. 

Recently I mapped some keys to executable calls, this allows me to switch between my various desktops easily, and everything worked fine.

Today I reinstalled Windows (for other reasons) and now when running `.\VirtualDesktop.exe "-Switch:Desktop 1"` I sometimes lose the focus on my last window, and sometimes I don't.

I really don't understand what's causing this, I went from never having the taskbar flashing orange on the icon to almost always flashing and having to ALT+TAB or clicking on the window.

**Comment by MScholtes** [comment]
Hello @shellwhale,

you might see here: https://superuser.com/questions/1332330/how-to-disable-flashing-icons-in-windows-10-taskbar

Greetings

Markus

**Comment by shellwhale** [comment]
Thanks for the tip @MScholtes but unfortunately I already tried that on my new system and it doesn't work. Also, I just checked the registry on my old system (where this works) and the registry values are the default ones. 

I noticed (on the new system, where that doesn't work) that the cursor stays on the terminal after running `.\VirtualDesktop.exe "-Switch:Desktop 1"`. I noticed that because the keys I pressed inside the other virtual desktop showed up in the console prompt on the first desktop. The cursor doesn't move to the new desktop.

**Comment by shellwhale** [comment]
https://user-images.githubusercontent.com/36083584/225091208-a0e3d035-3b27-4b85-9d0e-b7e7b453ab8a.mp4

**Comment by shellwhale** [comment]
https://user-images.githubusercontent.com/36083584/225094328-0a1c028e-7e9b-4b54-9899-79b5a3e44ac1.mp4

Same thing but on my old system. This works, but I don't know why.

**Comment by shellwhale** [comment]
I don't quite understand what was @bugwheels94 solution to solve this. @MScholtes do you understand what he meant by this ? 

> I have now set up this repo inside AHK and it works

**Comment by MScholtes** [comment]
Hallo @shellwhale,

**VirtualDesktop** does not care about activated windows or where the focus is. It simply ignores it and works on virtual desktops. You have to find the solution somewhere else.

Greetings

Markus

**Comment by bugwheels94** [comment]
@shellwhale I hid the taskbar completely(using nircmd) and flashing was happening or not happening but it did not bother me at all. I never use taskbar anyways. In windows 11, though I dont notice this flashing thing at all.

**Comment by bugwheels94** [comment]
MY AHK file


; === SYMBOLS ===
; !   <- Alt
; +   <- Shift
; ^   <- Ctrl
; #   <- Win
; For more, visit https://autohotkey.com/docs/Hotkeys.htm


; ===========================
; === END OF INSTRUCTIONS ===
; ===========================

#1::Run cmd.exe /c "D:\Softwares\VirtualDesktop-master\VirtualDesktop11 /Switch:0",,hide
#2::Run cmd.exe /c "D:\Softwares\VirtualDesktop-master\VirtualDesktop11 /Switch:1",,hide
#3::Run cmd.exe /c "D:\Softwares\VirtualDesktop-master\VirtualDesktop11 /Switch:2",,hide
#4::Run cmd.exe /c "D:\Softwares\VirtualDesktop-master\VirtualDesktop11 /Switch:3",,hide
#q::Run cmd.exe /c "D:\Softwares\VirtualDesktop-master\VirtualDesktop11 /Switch:4",,hide
#w::Run cmd.exe /c "D:\Softwares\VirtualDesktop-master\VirtualDesktop11 /Switch:5",,hide
#e::Run cmd.exe /c "D:\Softwares\VirtualDesktop-master\VirtualDesktop11 /Switch:6",,hide
!1::Run cmd.exe /c "D:\Softwares\VirtualDesktop-master\VirtualDesktop11 /Switch:7",,hide
!2::Run cmd.exe /c "D:\Softwares\VirtualDesktop-master\VirtualDesktop11 /Switch:8",,hide
!3::Run cmd.exe /c "D:\Softwares\VirtualDesktop-master\VirtualDesktop11 /Switch:9",,hide
!4::Run cmd.exe /c "D:\Softwares\VirtualDesktop-master\VirtualDesktop11 /Switch:10",,hide
!q::Run cmd.exe /c "D:\Softwares\VirtualDesktop-master\VirtualDesktop11 /Switch:11",,hide
!w::Run cmd.exe /c "D:\Softwares\VirtualDesktop-master\VirtualDesktop11 /Switch:12",,hide
!e::Run cmd.exe /c "D:\Softwares\VirtualDesktop-master\VirtualDesktop11 /Switch:13",,hide
#!Space::Run cmd.exe /c "D:\Softwares\nircmd-x64\nircmd.exe win trans class Shell_TrayWnd 256",,hide
#Space::Run cmd.exe /c "D:\Softwares\nircmd-x64\nircmd.exe win trans class Shell_TrayWnd 255",,hide

**Comment by shellwhale** [comment]
Because I use the taskbar from time to time I'm now using [https://github.com/hwtnb/SylphyHornPlusWin11](SylphyHornPlus) instead
