### ISSUE TITLE
Powershell version throws the error

### ISSUE THREAD

**Issue by rifaterdemsahin** [MScholtes/VirtualDesktop#26]
![image](https://user-images.githubusercontent.com/5270036/127388549-461e8ad7-25fc-462d-8c18-5ccb210c4dff.png)

Should i go for the csharp version

**Comment by MScholtes** [comment]
Hello rifaterdemsahin,
I think you mixed up the repositories: the powershell version of the virtual desktop toolset is in the [PSVirtualdesktop repository](https://github.com/MScholtes/PSVirtualDesktop).

I guess the error has something to do with the Windows and/or Powershell version. can you tell which versions you are using?

An easy way to determine both isthe output of the variable **$PSVersionTable** in Powershell.

Greetings

Markus

**Comment by MScholtes** [comment]
Closed since no reaction
