### ISSUE TITLE
Request:OnDesktopChange

### ISSUE THREAD

**Issue by itzjakm** [MScholtes/VirtualDesktop#28]
As I don't know a lot of c#, I don't know if this is possible.
Request: A parameter to specify an exe (or any program) and run it on Virtual Desktop Change.
I want this feature, because I'm comming from another library for Virtual Desktops on AutoHotkey, that is not compatible anymore with the lastest builds (and Windows 11). I'm trying to recreate all their functions with this repo and I can't make this one.
Thank You.

**Comment by itzjakm** [comment]
To clarify, (I don't know if its posible), this would have to be some sort of native thing, that not only get's fired on /Switch but also on Desktop Switch outside of this library.

**Comment by NyaMisty** [comment]
Use this: https://github.com/mntone/VirtualDesktop/tree/develop
which provides you with IVirtualDesktopNotification

**Comment by itzjakm** [comment]
Yes, But as I said, I don't know c#, so I'm not sure how to install it or run it...😢

**Comment by MScholtes** [comment]
Hello itzjakm,

my virtual desktop utility is written as a "one shot" program: This means that _VirtualDesktop_ starts, processes the tasks passed via parameters and then exits. For this reason, there is no possibility to wait for an event or notification, this is by design.

Grabacr07 seems to have given up its development unfortunately, but maybe someone can help you with one of the more advanced forks? The hint of NyaMisty might be very helpful.

Greetings

Markus

**Comment by itzjakm** [comment]
Ok, Thank You.
For now I just added a timer every few seconds to check current desktop, + every time the shorcut keys are clicked.
If  @NyaMisty  could help me with that repo it would be wonderful.
Closing for now...

**Comment by widavies** [comment]
I have working code for this on Windows 11 21H2 and 22H2, I can submit a pull request but as this library is more designed as a one-shot application, maybe it's better suited somewhere else

**Comment by MScholtes** [comment]
Hello @widavies,

thank you for your comment, but as stated there is no need for notifiactions in my project **VirtualDesktop**.

Maybe you can help in other projects like https://github.com/Grabacr07/VirtualDesktop, https://github.com/zgdump/windows-virtualdesktopindicator, https://github.com/newlooper/VirtualSpace, https://github.com/reserfodium/VirtualDesktopIndicator or https://github.com/lutz/VirtualDesktopNameDeskband or others.

Greetings

Markus
