### ISSUE TITLE
Error Message Compiling

### ISSUE THREAD

**Issue by JohannesBeiser** [MScholtes/VirtualDesktop#3]
Hey there. 

im having problem compiling the file getting following message insice the console:

 _This compiler is provided as part of the Microsoft (R) .NET Framework, but only supports language versions up to C# 5, which is no longer the latest version. For compilers that support newer versions of the C# programming language, see http://go.microsoft.com/fwlink/?LinkID=533240_

Im still not sure this is what I need. Does it "add" new commands to the command line? Like if I can create a .bat or .cmd with this that allows me to switch desktops this would be wonderful.
Im trying to create a Rainmeter skin that allows to switch desktops by moving the mouse to the display edge either left or right. Only problem: haven't found a way yet to switch virtual Desktops with the command line

**Comment by MScholtes** [comment]
Hello Johannes,

the message you get compiling is only an advertising, not an error. It is a reference to the new .NET Framework Compiler Roslyn.

When you compile VirtualDesktop, you get an command line executable that you can use in batches as you suppose.

Markus
