### ISSUE TITLE
Example of a request to move the currently active window to the specified desktop

### ISSUE THREAD

**Issue by photkey** [MScholtes/VirtualDesktop#33]
Really like this project, it's awesome. But I'm not a programmer, I'm not familiar with the command line, so I'd like to request a command line example: move the currently active window to the desktop named "Demo".
Windows 11

**Comment by MScholtes** [comment]
Hello @photkey,

I guess
```
virtualdesktop11.exe /getdesktop:Demo /MoveActiveWindow
```
will do the job (or in short: _virtualdesktop11 gd:Demo maw_).

Greetings

Markus

**Comment by photkey** [comment]
Thank you very much, this is exactly the example I needed. However, testing found that it didn't do what I wanted, it wasn't quite what I thought it would do. But no matter, with this example, I already know how I can implement the functionality I need. Thanks again, this project is really great and I hope it will be maintained forever.
I'm going to use this project to implement a series of very cool actions to show my friends through AHK.

**Comment by MScholtes** [comment]
Closed since issue is solved
