### ISSUE TITLE
Anyone have the .exe?

### ISSUE THREAD

**Issue by mishaxz** [MScholtes/VirtualDesktop#34]
is there anywhere I could download the .exe?

I really would like to be able to pint some shortcuts to my taskbar on Windows Server 2019 so I click them to go the left or right virtual desktop.

**Comment by MScholtes** [comment]
Hello @mishaxz,

there is no need to download the executable. Download the source files to a directory, open this in Windows Explorer and doubleclick on **Compile.bat** and you're done (even on Windows Server 2019).

Greetings

Markus

**Comment by mishaxz** [comment]
thanks, will do
