### ISSUE TITLE
Broken on Win11 build 22581

### ISSUE THREAD

**Issue by tauvinen** [MScholtes/VirtualDesktop#35]
...from Windows beta channel, but I guess as they have changed the taskbar quite heavily it will affect also the release version, once out.

And the problem description: no visible errors, just does not change the desktop.

**Comment by MScholtes** [comment]
Got no build 22581 'til now, check this when it arrives.

**Comment by Slion** [comment]
I have a similar issue using that other library:
https://github.com/Grabacr07/VirtualDesktop/issues/74

Could you explain to me how I can determine the CLSID from those interfaces?
I was trying to work it out with `oleview.exe` without luck so far.

**Comment by MScholtes** [comment]
@NyaMisty made a short explanation here: https://github.com/mntone/VirtualDesktop/pull/1#issuecomment-922269079

With a little luck step 1 is sufficient (in opposite to what @NyaMisty told you can get the new CLSIDs in step 1 too).

Greetings

Markus

**Comment by NyaMisty** [comment]
But I'm on 22598 and my fork works flawlessly

**Comment by Slion** [comment]
> But I'm on 22598 and my fork works flawlessly

Could this have to do with the method used to fetch the interfaces, by Name or by Id?

**Comment by Slion** [comment]
> But I'm on 22598 and my fork works flawlessly

You mean this one: https://github.com/NyaMisty/VirtualDesktop

It looks like quite lot has changed in the main repository since your fork though.
Does it work for .NET 6?
Are you publishing the NuGet somewhere?

**Comment by MScholtes** [comment]
Hello @Slion,

I'm a bit indignant now.

I downloaded the latest Insider version and installed it in a virtual machine, only to find out that everything works fine with my **VirtualDesktop** tool (similar to what @NyaMisty already described for his fork of the @Grabacr07 tool). I could have saved myself the work!

Please use only the repository that is affected for issues and discussions!

I am therefore closing this issue as it has been resolved.

Markus

**Comment by Slion** [comment]
@MScholtes sorry for the misunderstanding. I never meant to imply I had an issue with your tool, @tauvinen opened that issue and it looked similar to my issue with @Grabarc07 library so I thought linking both issues together could help resolve them.

Still I'm grateful for your time and support, it's been most useful to me.

**Comment by NyaMisty** [comment]
Both tool have fork, pls see the repo network to see my fork (as they are having the same name)
