### ISSUE TITLE
Windows 1809 - Broken API

### ISSUE THREAD

**Issue by CHacker24** [MScholtes/VirtualDesktop#4]
Just upgraded to 1809 and it seems as if the API is once broken again. If you find the time to fix this, my workflow would be foxed, too and I'd be very thankful ;-)

**Comment by CHacker24** [comment]
CLSIDs for **IApplicationView** and **IApplicationViewCollection** have changed. The new ones in Win1809 are:

- 372E1D3B-38D3-42E4-A15B-8AB2B178F513 for IApplicationView and 
- 1841C6D7-4F9D-42C0-AF41-8747538F10E5 for IApplicationViewCollection

Changing those two in the code and compiling did the trick for me. At least my minimal vDesktop switching requiremnts.

**Comment by MScholtes** [comment]
Accepted the request and added some minor changes.
Hope the new version is fine since I do not have Windows 10 1809 to test.

**Comment by TChristoph** [comment]
Great. Love your lib so much, I could not find any other working after all googling!
