### ISSUE TITLE
Split VirtualDesktop in CLI and library

### ISSUE THREAD

**Issue by korpa** [MScholtes/VirtualDesktop#40]
Hi Markus,

I use parts of your great work in https://gitlab.com/korpa/virtdeskbar

![image](https://user-images.githubusercontent.com/2982785/194086311-89b6841b-32aa-4d18-964b-3810f17f8f39.png)

Sadly maintaining this for every Windows version will be a mess. Therefore would it be possible to split your CLI and the library. Your CLI and virtdeskbar then could use the library. Furthermore it would be really great if this library would have a proper Windows version detection. Don't know if this possible as I'm a totally C# noob.

**Comment by MScholtes** [comment]
Hello @korpa,

this is a leisure project, so I did not make a library intentionally. I do not have the time or ressources to support a library or an executable.

I do not know (and don't have the time to do research) how to change COM-Guids at runtime depending on the windows version. I think you might find information here: https://github.com/Grabacr07/VirtualDesktop. This is a great repository, but is not maintained for a longer time.

Greetings

Markus
