### ISSUE TITLE
Windows 11 update breaks app

### ISSUE THREAD

**Issue by JackBuilt** [MScholtes/VirtualDesktop#42]
After I installed Version 22H2, it errors when trying to get desktops.

System.Runtime.InteropServices.COMException: 'A null reference pointer was passed to the stub. (Exception from HRESULT: 0x800706F4)'

internal static IVirtualDesktop GetDesktop(int index)
{
   ...
   VirtualDesktopManagerInternal.GetDesktops(IntPtr.Zero, out desktops);
   ...
}

**Comment by MScholtes** [comment]
Please use **VirtualDesktop11Insider.cs** for **22H2**, since the former Insider version has been released now.

I will rename the files in the repository soon acccording to the actual situation.

Greetings

Markus

**Comment by JackBuilt** [comment]
Thank you Markus! Using that file worked perfectly and I'm back up and running once again.
I really appreciate this project you've uploaded. It is extremely useful.

**Comment by MScholtes** [comment]
Hello @JackBuilt,

for your information: I renamed the files to reflect the new 21H2 version of Windows 11.

Greetings

Markus
