### ISSUE TITLE
Issue with /GetDesktop:<n|s> in VirtualDesktop11Insider.cs

### ISSUE THREAD

**Issue by EGruwez** [MScholtes/VirtualDesktop#43]
I used the getdesktop to move the active window to another desktop as such:
VirtualDesktop11Insider.cs.exe /getdesktop:desktopname | VirtualDesktop11Insider.cs.exe /moveactivewindow
It mover the active window always to desktop nr 0. In other words getdesktop passes 0 in the pipe instead of the desktop number.
What goes wrong? or what do i do wrong.
Thanks

**Comment by MScholtes** [comment]
Hello @EGruwez,

the solution is very easy: **Virtualdesktop** simply does not read the shell pipeline (but outputs to it), it only hands the value to the next parameter.
The solution for your issue is to use:
```
VirtualDesktop11Insider.cs.exe /getdesktop:desktopname /moveactivewindow
```

Greetings

Markus

**Comment by EGruwez** [comment]
Thank you Markus !!!
