### ISSUE TITLE
Windows Insiders fails again

### ISSUE THREAD

**Issue by NyaMisty** [MScholtes/VirtualDesktop#46]
I'm tired of cat-and-mouse game with Microsoft. I've made a script to download and analyze PDB symbols to automatically extract GUID and some COM method.

https://github.com/NyaMisty/GetVirtualDesktopAPI_DIA

**Comment by MScholtes** [comment]
Hello @NyaMisty,

this sounds really great. I will try it out the next few days.

Greetings
Markus

**Comment by MScholtes** [comment]
Microsoft did a strange thing with Windows 11 Insider Dev: they lowered the build number from 25309 to 23403 on March 8, 2023. That's weird.

Version checking might need to be corrected.

**Comment by NyaMisty** [comment]
@MScholtes That's intended. The original Dev branch was renamed into Canary (25XXX).
At the same time M$ introduced Dev branch that sits between Canary & Beta, and is using (23XXX).

**Comment by MScholtes** [comment]
Hello @NyaMisty,

I know, intended and weird. That makes it even worse!

Greetings

Markus

**Comment by MScholtes** [comment]
Thank you very much for your help
