### ISSUE TITLE
VD not working for me (on Windows 11 Insider build 25252)

### ISSUE THREAD

**Issue by j-standfast** [MScholtes/VirtualDesktop#47]
Hi, first off thanks for doing this. It's a cool project, and needed!

VD doesn't seem to be working for me, though. None of the methods triggering anything useful.

I noticed that VD.getCount() returns 0, and that my build (Windows 11 Insider 25252) may be later than the last that I saw commented at one point in the code).

I totally understand the nature of this project. If you happen to know what's up here, much appreciated!

**Comment by NyaMisty** [comment]
Not working since 25211.
But in fact you shouldn't even be able to run it because it will fail at initializing.

**Comment by j-standfast** [comment]
Interesting, got it. Too bad!

------- Original Message -------

**Comment by NyaMisty** [comment]
After investigating, the change happened at 25158.1000 update.
You can simply use my branch at https://github.com/NyaMisty/VirtualDesktop_, which usually updates for Insider faster than this repo because I'm on Insider myself LOL

**Comment by j-standfast** [comment]
Thanks very much! I'll look into it!

**Comment by MScholtes** [comment]
Hello @j-standfast,

I've added _VirtualdesktopInsider.cs_ with the adjustments of @NyaMisty to support Windows 11 Insider.

Greetings

Markus

**Comment by j-standfast** [comment]
Hey thanks!
