### ISSUE TITLE
move or start a program

### ISSUE THREAD

**Issue by PeterM32** [MScholtes/VirtualDesktop#53]
hello, 
thank you first of all for the great program. I would like to start or move a program with the name "123.exe" on the second desktop. Is this possible? Could you give me the code for it, since I don't really know my way around?

Thanks for your help.

greetings

**Comment by MScholtes** [comment]
Hello @PeterM32,

VirtualDesktop is no program starting utility. But when your program 123.exe is running you can move the window to the second desktop with:
```
virtualdesktop /GetDesktop:1 /MoveWindow:123
```

Greetings

Markus

**Comment by PeterM32** [comment]
thank you for your help... I can combine this further

**Comment by MScholtes** [comment]
I think this is solved...
