### ISSUE TITLE
Execute a Program on Specific Desktop in Windows 11 (Willing to payfor this)

### ISSUE THREAD

**Issue by vitralsoft** [MScholtes/VirtualDesktop#55]
I am using Virtual Desktops as a productivity tool.
However, I can't find anywhere a working solution in Windows 11 for the following:

I want to **launch** a shortcut or app
in **specific Virtual Desktops** in Windows 11.

A way to take a path to exe and add 
a desktop parameter  such as 
"path/to/exe" -additional-parameters" -desktop 4

This would dramatically improve my daily organization.
This is the most comprehensive project around Virtual Desktops I've seen for Windows 11 so

Please, If you develop such feature, I would be willing to financially contribute

**Comment by MScholtes** [comment]
Hello @vitralsoft,

as far as I know Windows provides no possibiltiy to start a program on a specific virtual desktop, programs always start on the current virtual desktop. So unfortunately I cannot help.

A workaround might be a command line sequence like this (maybe in a batch file), this example starts notepad.exe on a new desktop and then returns to the current desktop:
```cmd
virtualdesktop -GetCurrentDesktop
set DesktopNumber=%ERRORLEVEL%
virtualdesktop -new -switch
start notepad.exe
virtualdesktop -Getdesktop:%DesktopNumber% -Switch
```

And thank you for the offer of payment. But this is a project I do for fun and I want to keep it that way.

Greetings

Markus

**Comment by MScholtes** [comment]
Closed due to inactivity
