### ISSUE TITLE
Windows 1809

### ISSUE THREAD

**Issue by starik1968** [MScholtes/VirtualDesktop#6]
Hello, if I try to move an app, how can I get the name for the process to move? Tried it with different programms, only Essential PIM could moves with mv:EssentialPIM and the tool WInLister, mw:firefox e.g. failed. What went wrong?

Thanks in advance

cu
Friedrich

**Comment by starik1968** [comment]
Hi Markus, great! Did what I wanted, I have identified the processes I needed to identify. Great tool! cu Friedrich

**Comment by MScholtes** [comment]
You're welcome

Markus
