### ISSUE TITLE
SetDesktopName

### ISSUE THREAD

**Issue by guipalazzo** [MScholtes/VirtualDesktop#60]
Hello, I'm having issues when trying to rename the virtual desktop, by calling SetDesktopName.

The method do some marshalling on the name string, but it uses the HString type. According to[ this link](https://learn.microsoft.com/en-us/dotnet/standard/native-interop/customize-struct-marshalling), HSTRING marshalling is not supported in .NET 5 or newer, so I'm not sure how the renaming should be conducted in this case.

"_When using a WinRT-based API, you may need to marshal a string as an HSTRING. Using the [UnmanagedType.HString](https://learn.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.unmanagedtype#system-runtime-interopservices-unmanagedtype-hstring) value, you can marshal a string as a HSTRING. HSTRING marshalling is only supported on runtimes with built-in WinRT support. WinRT support was [removed in .NET 5](https://learn.microsoft.com/en-us/dotnet/core/compatibility/interop/5.0/built-in-support-for-winrt-removed), so HSTRING marshalling is not supported in .NET 5 or newer_."

I've tried to change it from UnmanagedType.HString to UnmanagedType.LPWStr, but I then get a "System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt". Even though my knowledge is not that deep on marshalling objects, I was able to use UnmanagedType.LPWStr marshalling in this past with no protected memory issues. Obviously and unfortunately, I couldn't figure out what is the issue in this case

Could you please assist?

**Comment by MScholtes** [comment]
Hello @guipalazzo ,

**.Net 5** and higher (formerly **.Net Core**) is a completely different version of **.Net** than the **.Net Framework** (formerly **.Net**), where the current version is **4.8x**.
**.Net Core** is a cross-platform product that runs on **Linux** and **MacOS** too, for example, and therefore does not support _Windows_-specific functions (at least _Microsoft_ is in the process of gradually removing them from **.Net Core**).
For this reason, the compilation of **VirtualDesktop** with **.Net Core** does not work and does not make sense, as _virtual desktops_ are _Windows_-specific. Please use **.Net Framework 4.x** as target platform or directly the attached script **Compile.bat**.

Greetings

Markus

**Comment by MScholtes** [comment]
Hello @guipalazzo,

my application is based on .Net Framework as it is targeting windows spezific features (so is WPF). There is no need to use or support .Net Core, so I don't.

Good luck with it

Markus

**Comment by MScholtes** [comment]
P.S. in my companion project [PSVirtualDesktop](https://github.com/MScholtes/PSVirtualDesktop) I define a class **HString** that might be useful for you.
