### ISSUE TITLE
Flagged by Virus Scanner

### ISSUE THREAD

**Issue by movme** [MScholtes/VirtualDesktop#61]
I've been using VirtualDesktop11.exe for about a month and this morning my Virus Scanner (Vipre Enterprise) flagged it as malicious, any idea why?

`The content of this page has been identified as malicious : Gen:Variant.Lazy.352990. `

**Comment by movme** [comment]
WIth a new set of definitions today, VirtualDesktop11.exe is no longer flagged as malicious -- very strange!!

**Comment by MScholtes** [comment]
Hello @movme,

I think there were errors in the signatures that Vipre corrected. So everything seems to be fine now.

Greetings

Markus

**Comment by MScholtes** [comment]
Closed for no reaction
