### ISSUE TITLE
Error in Windows 11 22H2

### ISSUE THREAD

**Issue by nevillekatila** [MScholtes/VirtualDesktop#62]
It doesn't work in Windows 11 version 22H2 as it throws a System.InvalidCastException.

Could you please add an updated file for this?

![cmd-error-Win11-22H2](https://github.com/MScholtes/VirtualDesktop/assets/24270566/7cbe00d6-4af1-45f7-88fe-7cc60ccfa860)

**Comment by MScholtes** [comment]
Hello @nevillekatila,

sorry about the error. 
To analyze I have to know which binary you are using (name of source/binaryfile) and whether it is precompiled or self-compiled.
I need to know your computer environment: Windows version (as displayed by Winver or Ver), 64- or 32-Bit Windows or .Net, if self-compiled .Net version.

Greetings

Markus

**Comment by nevillekatila** [comment]
Hi @MScholtes 

I have downloaded and extracted the .zip file, then run Compile.bat to get the compiled versions of each.
![compliled-using-compile-bat](https://github.com/MScholtes/VirtualDesktop/assets/24270566/a3f26f22-7dbb-4c1c-a19c-07171bb9c181)

I have tried it on 2 different Win 11 64 bit computers having build versions of 22621.1702 and 22621.1848
![Winver-cmd-1](https://github.com/MScholtes/VirtualDesktop/assets/24270566/32cbda12-0d41-49a8-ad80-219b07c29ebc)
![Winver-cmd-2](https://github.com/MScholtes/VirtualDesktop/assets/24270566/9bd6497a-e838-4006-96f9-fa0cb722373c)

It runs on Windows 10 just fine, please let me know if I'm doing something wrong here in Windows 11.

Thanks,
Neville

**Comment by nevillekatila** [comment]
Hi @MScholtes 

Yes, it worked with Virtualdesktop11.exe in Windows 11 22H2

Apologies for the false alarm, I was internally using the command Virtualdesktop.exe /GetCurrentDesktop to get the current desktop name in Windows 11 as I was doing on my own computer which is running Windows 10.

Since we're on the topic I would like to ask if we are supposed to use virtualdesktop11-21h2.cs for Windows 11 21H2 and virtualdesktop11.cs for all other versions of Windows 11?

Thanks,
Neville Katila

**Comment by MScholtes** [comment]
Hello @nevillekatila,

ok, I'm quite glad that this was a mistake. Had no idea where to search...

Yes, Virtualdesktop11.cs is for Windows 11 22H2, the Insider version shall work with Windows 11 Insider but is not really supported (who knows what Microsoft does the next day).

Greetings

Markus

**Comment by popstas** [comment]
Hello, I have same issue, all these commands causes `System.InvalidCastException`:
```
VirtualDesktop.exe /li /v
VirtualDesktop11.exe /li /v
VirtualDesktop11-21H2.exe /li /v
VirtualDesktopInsider.exe /li /v
VirtualDesktopServer2016.exe /li /v
VirtualDesktopServer2022.exe /li /v
```

`VirtualDesktop11.exe /?`: v1.13
`winver`: 22H2 22621.2115

Compiled with Compile.bat
