### ISSUE TITLE
Change name of desktop

### ISSUE THREAD

**Issue by mmaukii** [MScholtes/VirtualDesktop#63]
Thanks for the great tool again!! Do you see a possibility to implement a function to change the name of the virtual laptop?

**Comment by MScholtes** [comment]
Hello @mmaukii,

is there a typo in your request? Or what do you mean with "virtual laptop"?

**VirtualDesktop** can rename desktops with the parameter _/Name_, for example
```
VirtualDesktop /getdesktop:0 "/name:First Desktop"
```

Greetings

Markus

**Comment by mmaukii** [comment]
oh did not see that! yeah it was an typo. altough virtal laptops would also be a nice idea.

Thanks for the fast reply

**Comment by MScholtes** [comment]
Closed
