### ISSUE TITLE
Exception TYPE_E_ELEMENTNOTFOUND

### ISSUE THREAD

**Issue by Taster-git** [MScholtes/VirtualDesktop#65]
Hi @MScholtes 

When handle/ApplicationView/AppId of sticky notes are passed to these methods 
```
GetWindowDesktopId(IntPtr topLevelWindow)
IsViewPinned(IApplicationView applicationView)
IsAppIdPinned(string appId)
```
then **TYPE_E_ELEMENTNOTFOUND** exception occurs.

Test OS Info: Win10, Build # 19045

Thanks.

**Comment by MScholtes** [comment]
I guess this is related to https://github.com/MScholtes/VirtualDesktop/issues/66?

I need more explanation what error occurs with VirtualDesktop.

Greetings

Markus

**Comment by MScholtes** [comment]
Closed since it interferes with actual issues because of the Windows 11 August Preview Patch.
