### ISSUE TITLE
Unknown/Invalid Virtual Desktop Id of PinnedWindow and PinnedApplication

### ISSUE THREAD

**Issue by Taster-git** [MScholtes/VirtualDesktop#66]
Unknown/Invalid Virtual Desktop Id of PinnedWindow and PinnedApplication which does not matched with any already opened Virtual desktops.

**Comment by MScholtes** [comment]
That is obvious, since a pinned app or window is on all desktops. Returning a single existing GUID would be wrong.
A reserved GUID is returned instead.

Please stop asking me programming questions!

Greetings Markus
