### ISSUE TITLE
Broken in 22621?

### ISSUE THREAD

**Issue by michalgregor** [MScholtes/VirtualDesktop#67]
It seems that the tool is broken again in Win11 on 10.0.22621 Build 22621.

I am getting this error (with the VirtualDesktopInsider version, but I tried all, none works):

```
VirtualDesktopInsider.exe -GetCurrentDesktop -Calc:+1 -MoveWindowHandle: 1775152

Unhandled Exception: System.TypeInitializationException: The type initializer for 'VirtualDesktop.DesktopManager' threw an exception. ---> System.InvalidCastException: Specified cast is not valid.
   at VirtualDesktop.IServiceProvider10.QueryService(Guid& service, Guid& riid)
   at VirtualDesktop.DesktopManager..cctor()
   --- End of inner exception stack trace ---
   at VirtualDesktop.Desktop.get_Current()
   at VDeskTool.Program.Main(String[] args)
```

**Comment by MScholtes** [comment]
Hello @michalgregor,

there is limited support for Insider versions. I'm researching this in my neighbor project in this issue https://github.com/MScholtes/PSVirtualDesktop/issues/27.

Since I guess that build 22631 will be the new Win 11 23H2 I do not support Insider 22621 which will die and in some releases work, in some not.

Greetings

Markus

**Comment by KonaKoex** [comment]
have same problem on win11 22H8 update,today.

**Comment by michalgregor** [comment]
Just out of curiosity – are these COM interfaces documented somewhere or how do you actually find the proper GUIDs and everything?

**Comment by MScholtes** [comment]
Hello @michalgregor,

the COM API is not documented and not supported and to illustrate this Microsoft changes the API including GUIDs every few months. There is a small group of ~~Gallic warriors~~ enthusiasts trying to keep up.
You need debugging tools to find the actual API.


OK, I have made two attempts to find out what changed in my campagnion project [PSVirtualDesktop](https://github.com/MScholtes/PSVirtualDesktop):

The first attempt (attached VirtualDesktopV3.ps1) assumes that the API is the same from new Windows 11 build 22621 upwards.

The second attempt (attached VirtualDesktopV4.ps1) assumes that the API from new build 22621 onwards is the same as the API from Windows Insider Beta before 8 March 2023 and that another API applies from Insider Dev onwards.

Please remove the additional extension txt from the files and start Powershell in the directory of the scripts:

```powershell
. .\VirtualDesktopV3.ps1
Get-DesktopList
```

exit Powershell now, start a new Powershell session and then

```powershell
. .\VirtualDesktopV4.ps1
Get-DesktopList
````

Can you post what's happening?

Greetings

Markus

[VirtualDesktopV4.ps1.txt](https://github.com/MScholtes/VirtualDesktop/files/12426038/VirtualDesktopV4.ps1.txt)
[VirtualDesktopV3.ps1.txt](https://github.com/MScholtes/VirtualDesktop/files/12426039/VirtualDesktopV3.ps1.txt)

**Comment by Hyphen90** [comment]
Hi, today my systems also updates to KB5029351 and your tool did not work anymore (exception). I'm not taking place in the Windows Insider program.

**Comment by codemaster2837** [comment]
Hello, I can confirm this. After updating to 22621.2215, the script is running into an exception. I am not a member of the Windows Insider Program.

**Comment by doctarrwho** [comment]
V3 works, V4 throws an exception.

![image](https://github.com/MScholtes/VirtualDesktop/assets/70813119/03bfd2e0-91b9-43d3-9df6-2d8a3e21a93f)

![image](https://github.com/MScholtes/VirtualDesktop/assets/70813119/25282051-6748-4033-8dc5-e2d9faf75e15)

**Comment by FCrane** [comment]
This seems to work for the latest Windows versions:
```c++
// Windows 11 23H2
MIDL_INTERFACE("3F07F4BE-B107-441A-AF0F-39D82529072C")
IVirtualDesktop1123H2 : public IUnknown
{
public:
	virtual HRESULT STDMETHODCALLTYPE IsViewVisible(
		IApplicationView * pView,
		int* pfVisible) = 0;

	virtual HRESULT STDMETHODCALLTYPE GetID(
		GUID* pGuid) = 0;
};


// Windows 11 23H2
MIDL_INTERFACE("A3175F2D-239C-4BD2-8AA0-EEBA8B0B138E")
IVirtualDesktopManagerInternal1123H2 : public IUnknown
{
public:
	virtual HRESULT STDMETHODCALLTYPE GetCount(
		UINT * pCount) = 0;

	virtual HRESULT STDMETHODCALLTYPE MoveViewToDesktop(
		IApplicationView* pView,
		IVirtualDesktop1123H2* pDesktop) = 0;

	// Since build 10240
	virtual HRESULT STDMETHODCALLTYPE CanViewMoveDesktops(
		IApplicationView* pView,
		int* pfCanViewMoveDesktops) = 0;

	virtual HRESULT STDMETHODCALLTYPE GetCurrentDesktop(
//		HWND hWndOrMon,
		IVirtualDesktop1123H2** desktop) = 0;

	//// Since build 22H2
	//virtual HRESULT STDMETHODCALLTYPE GetAllCurrentDesktops(
	//	IObjectArray** ppDesktops) = 0;

	virtual HRESULT STDMETHODCALLTYPE GetDesktops(
	//	HWND hWndOrMon,
		IObjectArray** ppDesktops) = 0;

	virtual HRESULT STDMETHODCALLTYPE GetAdjacentDesktop(
		IVirtualDesktop1123H2* pDesktopReference,
		AdjacentDesktop uDirection,
		IVirtualDesktop1123H2** ppAdjacentDesktop) = 0;

	virtual HRESULT STDMETHODCALLTYPE SwitchDesktop(
	//	HWND hWndOrMon,
		IVirtualDesktop1123H2* pDesktop) = 0;

	// Since build 23H2
	virtual HRESULT STDMETHODCALLTYPE SwitchDesktopAndMoveForegroundView(
		IVirtualDesktop1123H2* pDesktop) = 0;

	virtual HRESULT STDMETHODCALLTYPE CreateDesktopW(
//		HWND hWndOrMon,
		IVirtualDesktop1123H2** ppNewDesktop) = 0;

	virtual HRESULT STDMETHODCALLTYPE MoveDesktop(
		IVirtualDesktop1123H2* pDesktop,
//		HWND hWndOrMon,
		int index) = 0;

	virtual HRESULT STDMETHODCALLTYPE RemoveDesktop(
		IVirtualDesktop1123H2* pRemove,
		IVirtualDesktop1123H2* pFallbackDesktop) = 0;

	// Since build 10240
	virtual HRESULT STDMETHODCALLTYPE FindDesktop(
		GUID* desktopId,
		IVirtualDesktop1123H2** ppDesktop) = 0;

	virtual HRESULT STDMETHODCALLTYPE GetDesktopSwitchIncludeExcludeViews(
		IVirtualDesktop1123H2 desktop,
		IObjectArray** unknown1,
		IObjectArray** unknown2) = 0;

	virtual HRESULT STDMETHODCALLTYPE SetDesktopName(
		IVirtualDesktop1123H2 desktop,
		PCSTR name) = 0;

	virtual HRESULT STDMETHODCALLTYPE SetDesktopWallpaper(IVirtualDesktop1123H2 desktop, PCSTR path) = 0;
	virtual HRESULT STDMETHODCALLTYPE UpdateWallpaperPathForAllDesktops(PCSTR path) = 0;
	virtual HRESULT STDMETHODCALLTYPE CopyDesktopState(IApplicationView pView0, IApplicationView pView1) = 0;
	//virtual HRESULT STDMETHODCALLTYPE GetDesktopIsPerMonitor(int* pResult) = 0;
	//virtual HRESULT STDMETHODCALLTYPE SetDesktopIsPerMonitor(bool state) = 0;
};

// Windows 11 23H2
MIDL_INTERFACE("B287FA1C-7771-471A-A2DF-9B6B21F0D675")
IVirtualDesktopNotification1123H2 : public IUnknown
{
public:
	virtual HRESULT STDMETHODCALLTYPE VirtualDesktopCreated(
		IObjectArray * p0,
		IVirtualDesktop1123H2* pDesktop) = 0;

	virtual HRESULT STDMETHODCALLTYPE VirtualDesktopDestroyBegin(
		IObjectArray* p0,
		IVirtualDesktop1123H2* pDesktopDestroyed,
		IVirtualDesktop1123H2* pDesktopFallback) = 0;

	virtual HRESULT STDMETHODCALLTYPE VirtualDesktopDestroyFailed(
		IObjectArray* p0,
		IVirtualDesktop1123H2* pDesktopDestroyed,
		IVirtualDesktop1123H2* pDesktopFallback) = 0;

	virtual HRESULT STDMETHODCALLTYPE VirtualDesktopDestroyed(
		IObjectArray* p0,
		IVirtualDesktop1123H2* pDesktopDestroyed,
		IVirtualDesktop1123H2* pDesktopFallback) = 0;

	virtual HRESULT STDMETHODCALLTYPE Unknown1(
		int nNumber) = 0;

	virtual HRESULT STDMETHODCALLTYPE VirtualDesktopMoved(
		IObjectArray* p0,
		IVirtualDesktop1123H2* pdesktop,
		int nFromIndex, int nToIndex) = 0;

	virtual HRESULT STDMETHODCALLTYPE VirtualDesktopRenamed(
		IVirtualDesktop1123H2* pdesktop,
		PCSTR name) = 0;

	virtual HRESULT STDMETHODCALLTYPE ViewVirtualDesktopChanged(
		IApplicationView* pView) = 0;

	virtual HRESULT STDMETHODCALLTYPE CurrentVirtualDesktopChanged(
		IObjectArray* p0,
		IVirtualDesktop1123H2* pDesktopOld,
		IVirtualDesktop1123H2* pDesktopNew) = 0;

	virtual HRESULT STDMETHODCALLTYPE VirtualDesktopWallpaperChanged(
		IVirtualDesktop1123H2* pdesktop,
		PCSTR path) = 0;
};
//   https://gitter.im/glsorre/amethystwindows?at=5ffd913403529b296be5e65d
//HRESULT Proc3(/* Stack Offset: 8 */[In] IObjectArray* p0, /* Stack Offset: 16 */[In] IVirtualDesktop* p1);
//HRESULT Proc4(/* Stack Offset: 8 */[In] IObjectArray* p0, /* Stack Offset: 16 */[In] IVirtualDesktop* p1, /* Stack Offset: 24 */[In] IVirtualDesktop* p2);
//HRESULT Proc5(/* Stack Offset: 8 */[In] IObjectArray* p0, /* Stack Offset: 16 */[In] IVirtualDesktop* p1, /* Stack Offset: 24 */[In] IVirtualDesktop* p2);
//HRESULT Proc6(/* Stack Offset: 8 */[In] IObjectArray* p0, /* Stack Offset: 16 */[In] IVirtualDesktop* p1, /* Stack Offset: 24 */[In] IVirtualDesktop* p2);
//HRESULT Proc7(/* Stack Offset: 8 */[In] int p0);
//HRESULT Proc8(/* Stack Offset: 8 */[In] IObjectArray* p0, /* Stack Offset: 16 */[In] IVirtualDesktop* p1, /* Stack Offset: 24 */[In] int p2, /* Stack Offset: 32 */[In] int p3);
//HRESULT Proc9(/* Stack Offset: 8 */[In] IVirtualDesktop* p0, /* Stack Offset: 16 */[In] FC_USER_MARSHAL* p1);
//HRESULT Proc10(/* Stack Offset: 8 */[In] IApplicationView* p0);
//HRESULT Proc11(/* Stack Offset: 8 */[In] IObjectArray* p0, /* Stack Offset: 16 */[In] IVirtualDesktop* p1, /* Stack Offset: 24 */[In] IVirtualDesktop* p2);
//HRESULT Proc12(/* Stack Offset: 8 */[In] IVirtualDesktop* p0, /* Stack Offset: 16 */[In] FC_USER_MARSHAL* p1);
//}


// Windows 11 23H2
MIDL_INTERFACE("0CD45E71-D927-4F15-8B0A-8FEF525337BF")	// W11: UNCHANGED
IVirtualDesktopNotificationService1123H2 : public IUnknown
{
public:
	virtual HRESULT STDMETHODCALLTYPE Register(
		IVirtualDesktopNotification1123H2* pNotification,
		DWORD * pdwCookie) = 0;

	virtual HRESULT STDMETHODCALLTYPE Unregister(
		DWORD dwCookie) = 0;
};

However, there is still 1 problem: the CurrentVirtualDesktopChanged notification never happens! 

ViewVirtualDesktopChanged arrives correctly, but CurrentVirtualDesktopChanged does not. What could be the reason?
``` 

Regards!

**Comment by FCrane** [comment]
It seems the "CurrentVirtualDesktopChanged" function was removed from "IVirtualDesktopNotification" interface - it is called when the wallpaper changes, which means the "next" function after "ViewVirtualDesktopChanged" is "VirtualDesktopWallpaperChanged" and not "CurrentVirtualDesktopChanged" like in previous versions...

Strange - the function seems to be important to detect when the user changes the virtual desktop. Does anybody have more info on this?

Regards!

**Comment by MScholtes** [comment]
Hello @FCrane,

cannot tell anything about virtual desktop notifications since this is not implemented in [VirtualDesktop](https://github.com/MScholtes/VirtualDesktop).

Greetings

Markus

**Comment by MScholtes** [comment]
Released a new version of **VirtualDesktop** today.

**VirtualDesktop11-23H2.cs** is intended to work with _Windows 11 22H2_ beginning with release 2215 and with the Insider versions of _Windows 11_.

As I do not have a test environment, this is associated with certain uncertainties...

Greetings

Markus

**Comment by michalgregor** [comment]
> Released a new version of **VirtualDesktop** today.
> 
> **VirtualDesktop11-23H2.cs** is intended to work with _Windows 11 22H2_ beginning with release 2215 and with the Insider versions of _Windows 11_.
> 
> As I do not have a test environment, this is associated with certain uncertainties...
> 
> Greetings
> 
> Markus

I reinstalled the update and tested, I can confirm that it works perfectly for my use case of moving windows to another desktop.

Keeping this working seems like it must be a lot of work for you with the changing interfaces. Is there any way to support your work (buying an app, donating some money, etc.)?

**Comment by FCrane** [comment]
> @FCrane
> 
> Current virtual desktop change is working, you have to remove the monitors parameter:
> 
> ```
> 
> 	virtual HRESULT STDMETHODCALLTYPE CurrentVirtualDesktopChanged(
> 		IObjectArray* p0,
> 		IVirtualDesktop1123H2* pDesktopOld,
> 		IVirtualDesktop1123H2* pDesktopNew) = 0;
> ```
> 
> TO:
> 
> ```
> 
> 	virtual HRESULT STDMETHODCALLTYPE CurrentVirtualDesktopChanged(
> 		IVirtualDesktop1123H2* pDesktopOld,
> 		IVirtualDesktop1123H2* pDesktopNew) = 0;
> ```

Hi! This is not working on my test systems for release 2215 and later... CurrentVirtualDesktopChanged is never called by the system, no matter which parameters are defined.

Regards!

**Comment by Ciantic** [comment]
@FCrane You need to remove all monitor parameters.

I'm using Rust these days but you can see the IVirtualDesktopNotification definition here:

https://github.com/Ciantic/VirtualDesktopAccessor/blob/rust/src/interfaces.rs on line 380 is equivalent Rust code.

Notice I have removed all IObjectArray (the monitor parameters) from other methods as well like destroyed, moved,... you have to do the same.

**Comment by FCrane** [comment]
@Ciantic: Great, thanks!!

**Comment by MScholtes** [comment]
Hello,

I released a new bug fix version 1.15 today - tested only against Windows 11 22H2.2215. 
According to Microsoft's will, this may become obsolete again with the September update.

It corrects issues with creating, removing and naming desktops on Windows 11 22H2.2215 (reason for the error: _SwitchDesktopAndMoveForegroundView_ is missing in 2215).

I do not know, if this works on Insider versions build 22631 and up. It would be helpful if you try
```cmd
VirtualDesktop11-23H2.exe /New
```
if you own an Insider version and post the result and the build number here.


Greetings

Markus

**Comment by MScholtes** [comment]
> > Released a new version of **VirtualDesktop** today.
> > **VirtualDesktop11-23H2.cs** is intended to work with _Windows 11 22H2_ beginning with release 2215 and with the Insider versions of _Windows 11_.
> > As I do not have a test environment, this is associated with certain uncertainties...
> > Greetings
> > Markus
> 
> I reinstalled the update and tested, I can confirm that it works perfectly for my use case of moving windows to another desktop.
> 
> Keeping this working seems like it must be a lot of work for you with the changing interfaces. Is there any way to support your work (buying an app, donating some money, etc.)?

Thank you very much for your offer but I'm (still) doing this for fun.

**Comment by slnz00** [comment]
Hey,

Inspired by @NyaMisty's solution ([GetVirtualDesktopAPI_DIA](https://github.com/NyaMisty/GetVirtualDesktopAPI_DIA)), I created a dumper that works with the latest versions of Windows 11:

[slnz00/VirtualDesktopDumper](https://github.com/slnz00/VirtualDesktopDumper)

I set up some virtual machines and created dumps for all the current live releases (including the insider versions). You can find these dumps in the dumper's repository.

I also tested your latest 23H2 release (v1.15), and it works great for all versions after `22621.2215`, except for the current canary build (`25941.1000`) where they reintroduced the `SwitchDesktopAndMoveForegroundView` function which was previously removed and caused issues in `22621.2215`.

A new `IVirtualDesktop` interface GUID has also been introduced. It can be extracted using the `IID_IVirtualDesktop2` symbol. However, it seems that using the old GUID still works and does not cause any issues.

**Comment by MScholtes** [comment]
Hello @slnz00,

thank you for your very valuable information.

Unfortunately, NyaMisty's Python script and yours are still not working for me. It would be very, very helpful if I could run them myself so I don't have to ask someone to run it for me every time.

I made an issue for that.

Greetings

Markus

**Comment by MScholtes** [comment]
Issue solved
