### ISSUE TITLE
Virtual Desktop Broken after KB5029351

### ISSUE THREAD

**Issue by iamsteelone** [MScholtes/VirtualDesktop#68]
Hi Markus

Getting the attached error since windows update KB5029351 (OS Build 22621.2215)

![image](https://github.com/MScholtes/VirtualDesktop/assets/29373666/1b6a14c4-e954-480d-8756-62b5a835f4bd)

**Comment by MScholtes** [comment]
Duplicate, see here https://github.com/MScholtes/VirtualDesktop/issues/67

**Comment by MScholtes** [comment]
Closed since duplicate
