### ISSUE TITLE
"Remove" function not working in VirtualDesktop11-23H2

### ISSUE THREAD

**Issue by BarRaider** [MScholtes/VirtualDesktop#69]
Thank you so much for your support and commitment to this project, and the quick update to support the latest Win11 update!

Wanted to update that the only issue found is the Remove function which doesn't seem to work.
In the exe it just says:
```
Removing virtual desktop number 1 (desktop 'Test1')
Error while processing '/Remove:Test1'
```

When directly calling the code I get the following exception:
```
System.Runtime.InteropServices.COMException (0x8002802B): Element not found. (Exception from HRESULT: 0x8002802B (TYPE_E_ELEMENTNOTFOUND))
```

**Comment by MScholtes** [comment]
Hello @BarRaider,

I released a new bug fix version 1.15 today - tested only against Windows 11 22H2.2215. 

According to Microsoft's will, this may become obsolete again with the September update.

Greetings

Markus

**Comment by Nocture** [comment]
I just want to show appreciation for your good work :) @MScholtes

**Comment by MScholtes** [comment]
Issue solved
