### ISSUE TITLE
suggestion

### ISSUE THREAD

**Issue by jonathan-annett** [MScholtes/VirtualDesktop#73]
*line 840 aprox in virtualDesktop.cs*
```cs
							case "WAITDESKTOPCHANGE":
							case "WDC":
							case "GETCURRENTDESKTOP": // get number of current desktop and display desktop name
							case "GCD":
								rc = VirtualDesktop.Desktop.FromDesktop(VirtualDesktop.Desktop.Current);
								switch(groups[1].Value.ToUpper()) {
									case "WAITDESKTOPCHANGE":
									case "WDC":
									System.Threading.Thread.Sleep(5);
									if (verbose) Console.WriteLine("Waiting for desktop to change from: '" + VirtualDesktop.Desktop.DesktopNameFromDesktop(VirtualDesktop.Desktop.Current) + "' (desktop number " + rc + ")");
									while (rc == VirtualDesktop.Desktop.FromDesktop(VirtualDesktop.Desktop.Current)) {
										System.Threading.Thread.Sleep(5);
									}
									break;						
								}
								if (verbose) Console.WriteLine("Current desktop: '" + VirtualDesktop.Desktop.DesktopNameFromDesktop(VirtualDesktop.Desktop.Current) + "' (desktop number " + rc + ")");
								break;
```

adds an option to wait until the user changes to another desktop
eg switch to desktop 2, then as soon as they move elsewhere yank them back to 0
```ps1
 .\VirtualDesktop.exe /switch:2  /WDC  /switch:0
```
 
if you prefer i can make a PR, however it's such a trivial change, you may prefer to just implement it yourself

**Comment by MScholtes** [comment]
Hello @jonathan-annett,

thank you for your suggestion.

But to be honest, I don't see the point in building a function that waits for a user to switch desktops.
**Virtualdesktop** is a tool to change desktops, not to wait for this.

Additionally I have the concept of making a One Shot Tool.

Greetings

Markus

**Comment by jonathan-annett** [comment]
All good. I've forked and moved on. Good luck with your project
