### ISSUE TITLE
Not working since last Windows update (Windows 11 22H2 Build 22621.2428)

### ISSUE THREAD

**Issue by nicoh67** [MScholtes/VirtualDesktop#75]
Hi,
For first, thanks a lot for your wonderful job!

I have problem since the last Windows update this night :

Every command shows me the issue below.

VirtualDesktop11.exe /LIST

Exception non gérée : System.TypeInitializationException: Une exception a été levée par l'initialiseur de type pour 'VirtualDesktop.DesktopManager'. ---> System.InvalidCastException: Le cast spécifié n'est pas valide.
   à VirtualDesktop.IServiceProvider10.QueryService(Guid& service, Guid& riid)
   à VirtualDesktop.DesktopManager..cctor()
   --- Fin de la trace de la pile d'exception interne ---
   à VirtualDesktop.Desktop.get_Count()
   à VDeskTool.Program.Main(String[] args)

**Comment by MScholtes** [comment]
Hello @nicoh67,

I think you have to use **VirtualDesktop11-23H2.exe** instead.
I'm sorry for the confusing filenames, I will clean up with the next update of **VirtualDesktop**.

Greetings

Markus

**Comment by nicoh67** [comment]
Thanks a lot, it works perfectly !

Greetings,
Nicolas
