### ISSUE TITLE
Active windows taskbar icons become invisible while changing active desktop

### ISSUE THREAD

**Issue by Sabin-DC** [MScholtes/VirtualDesktop#76]
Pretty much title, whatever i have active will eventually become invisible as an icon on the taskbar when swtiching, eventually enough that I dont know what is what. Not sure whats the issue, I just did a fresh reinstall of windows so was hoping it would fix it (done for other reasons), but it's there still, If need any other info please let me know

![image](https://github.com/MScholtes/VirtualDesktop/assets/56815136/c9445e32-4994-4fdd-9a25-7c21b5944bd6)

**Comment by analytic-garden** [comment]
I have tried every proposed solution I could find on the web; none worked.

The following work until you switch desktops
- restart Explorer
- clear Windows icon cache
- delete IRIS service
- run SFC and DISM - as far as I can tell this has never helped with anything
- clean boot
- uninstalling a Windows update, uninstalling the latest update didn't help. I don't know how far back you have to go.
- restart PC

Good luck

**Comment by MScholtes** [comment]
Hello @Sabin-DC,

do you have any idea what the process of the empty icon is? Can you right click on the icon and see a process name?

How did you switch the desktop? Does it happen even if Google Chrome is not running?

Greetings

Markus

**Comment by Sabin-DC** [comment]
> Hello @Sabin-DC,
> 
> do you have any idea what the process of the empty icon is? Can you right click on the icon and see a process name?
> 
> How did you switch the desktop? Does it happen even if Google Chrome is not running?
> 
> Greetings
> 
> Markus

Hi @MScholtes , this is a small list of the programs, you said process over program so sorry if I misunderstood, I just took the exe names per the tasklist. They are self descript.

Discord.exe
steam.exe
Spotify.exe
notion.exe
tabsoutlier (tab extension from chrome)
craft.exe
olk.exe (outlook)
code.exe (vscode)
notepad.exe
keypass.exe 

This happens with all these programs at least, randomly. Even if Chrome is closed, it will eventually happen on these icons.

How I use it:
Running AHK to execute a shortcut, which runs no-console on a BAT file on the following type of commands : 
"G:\Dev_Projects\Scripts\tools\VirtualDesktop.exe" "-Switch:Desktop 2"

I tested without my whole strange setup, so one CMD prompt per desktop, pasting the relevant text to jump from desktop to desktop, manually, and it still eventually makes the icons invisible.

I can always see the program by hovering, and maximizing it and then minimizing it again will restore the icon. Eventually after jumping enough times between desktops, they begin to disappear again.

Let me know if you need any other info or tests I can do to help.

Thanks!

Denis C

**Comment by MScholtes** [comment]
Hello @Sabin-DC ,

sorry for the late answer, I was ill for some days,

I organized a Win11 notebook and tried out. I can't recreate your problems, but I admit I do not use **AHK**, **Discord**, **Notion,** **Outlook**, **Steam**, **Spotify** or **Visual Studio Code** (but I do use **KeePass** and sometimes **notepad**).

I have no idea but for testing I guess you have to disable those programs temporary step-by-step to find out which does not harmonate with **VirtualDesktop**.

Greetings

Markus

**Comment by Sabin-DC** [comment]
> Hello @Sabin-DC ,
> 
> sorry for the late answer, I was ill for some days,
> 
> I organized a Win11 notebook and tried out. I can't recreate your problems, but I admit I do not use **AHK**, **Discord**, **Notion,** **Outlook**, **Steam**, **Spotify** or **Visual Studio Code** (but I do use **KeePass** and sometimes **notepad**).
> 
> I have no idea but for testing I guess you have to disable those programs temporary step-by-step to find out which does not harmonate with **VirtualDesktop**.
> 
> Greetings
> 
> Markus

Well it's tough because even windows windows this occurs on it seems, even the command prompt, or control panel/settings. It's very random and i've tried running the exe via CMD and powershell in admin, manually calling the switch, with the same results. Sometimes the icons show up, sometimes they vanish. There's no clear pattern and almost every app I have seems to be impact by this. I can't see any patterns with regards to how they were installed either

**Comment by MScholtes** [comment]
I assume that the issue no longer exists as there is no feedback.
