### ISSUE TITLE
Having issues on new released OS build 22631

### ISSUE THREAD

**Issue by Taster-git** [MScholtes/VirtualDesktop#77]
Hi @MScholtes 
I am facing issues with the new **OS build 22631**. Please keep an eye on this issue **from your precious time.**

After following errors with some apps like Windows File Explorer and even the Window Task Bar stays stuck in the background, behind all other Windows! We are unable to foreground them. Only logoff or Power restart solves this issue.

On desktop creation by the app's handle
**Process: explorer** -- Exception: Element not found. (0x8002802B (TYPE_E_ELEMENTNOTFOUND)) 
Error: IsPinApp. --App:explorer --MessageElement not found. (0x8002802B (TYPE_E_ELEMENTNOTFOUND))

**Process: snap15** -- Exception:Element not found. (0x8002802B (TYPE_E_ELEMENTNOTFOUND))
**Process: Twinkle Tray** -- Exception:Element not found. (0x8002802B (TYPE_E_ELEMENTNOTFOUND))

Thanks and Regards
Tester

**Comment by MScholtes** [comment]
Hello @Taster-git,

sorry for the late answer. I cannot tell much to the errors since they are not generated by VirtualDesktop.

Greetings

Markus

**Comment by Taster-git** [comment]
Hi @MScholtes .
Thanks for your reply. You means this errors are received from Windows API? 
Any remedy or suggestions please? 

Regards

**Comment by MScholtes** [comment]
Hello @Taster-git,

all I know is that these errors are not generated by my **VirtualDeskop** application. Cannot help on other projects.

Greetings

Markus

**Comment by Taster-git** [comment]
I observed many times that whenever I use this VirtualDesktop solution, then I face such type of error. It is random. Not easily reproducible. Anyhow, thanks for your reply.

**Comment by MScholtes** [comment]
I assume that the issue no longer exists as there is no feedback.
