### ISSUE TITLE
I think this might not work with Win11 Dev Insider build 23606

### ISSUE THREAD

**Issue by phazei** [MScholtes/VirtualDesktop#78]
I don't use this project, but I use another that used this project as reference.  So I tried to update that project with the newer Win11 23H2 GUID's and method prototypes you were using but that didn't work.  Then I found a 3rd project that had a similar issue someone recently reported and it turned out the newer Win 11 insider dev build uses a newer GUID that I don't think I saw you use here in this project.  I tried it out with my code and it did indeed seem to be the issue.  So I thought I'd point it out so you don't need to go hunting for the new GUID when the issue turns up.  You can find the new GUID in my pr for the first project: https://github.com/FuPeiJiang/VD.ahk/pull/62

**Comment by MScholtes** [comment]
Hello @phazei,
thank you for the information. As this is a private project and I don't use an Insider version of Windows, I often don't manage to keep up with the many fundamental changes from Microsoft.

I ask for your understanding.

Greetings

Markus

**Comment by willuhn** [comment]
Can confirm. VirtualDesktop11-23H2.exe  no longer works on 23H2 after installing the january update KB5034204.

Changing UID "A3175F2D-239C-4BD2-8AA0-EEBA8B0B138E" to "4970BA3D-FD4E-4647-BEA3-D89076EF4B9C" solved the issue:

```diff
--- VirtualDesktop11-23H2.cs    2024-01-24 11:44:46.045431100 +0100
+++ VirtualDesktop11-23H2-KB5034204.cs  2024-01-24 11:49:26.584646200 +0100
@@ -161,7 +161,7 @@

        [ComImport]
        [InterfaceType(ComInterfaceType.InterfaceIsIUnknown)]
-       [Guid("A3175F2D-239C-4BD2-8AA0-EEBA8B0B138E")]
+       [Guid("4970BA3D-FD4E-4647-BEA3-D89076EF4B9C")]
        internal interface IVirtualDesktopManagerInternal
        {
                int GetCount();
```

**Comment by MScholtes** [comment]
Hello,

does this apply only to the Insider Dev Channel? What about the Canary Channel, Beta Channel or Release Preview Channel and the productive version?

Greetings

Markus

**Comment by willuhn** [comment]
Productive. I don't use any beta/preview/insider versions. It's the regular 23h2 with the january update from today.

**Comment by MScholtes** [comment]
Ok, this is a very import information. I will check this.

Greetings

Markus

**Comment by iamsteelone** [comment]
Confirmed not working for me today after last nights update
![image](https://github.com/MScholtes/VirtualDesktop/assets/29373666/86716a91-5494-4d9e-93e6-30846aac283f)

**Comment by slnz00** [comment]
Hey @MScholtes,

The GUID of the `IVirtualDesktopManagerInternal` interface has been changed in the latest Windows update (`22631.3085`).

This is the current, working GUID for the interface: `53F5CA0B-158F-4124-900C-057158060B27`

You can also find the full dump here:
https://github.com/slnz00/VirtualDesktopDumper/blob/master/dumps/Win11-23H2-22631.3085.txt

Other than the GUID change, a new argument has also been introduced to the `SwitchRemoteDesktop` method. However, it shouldn't cause any issues as this method isn't used anywhere.

**Comment by MScholtes** [comment]
Hello out there,

I can commit the change with Windows 11 and the preview update to Win 11 23H2 (raises build from 3007 to 3085). The suggested solution by @slnz00 works. However, I will wait until the next mandatory update before making any adjustments, otherwise it will no longer work with Windows 11 without this update.

I'm a bit confused about the GUID "4970BA3D-FD4E-4647-BEA3-D89076EF4B9C" @willuhn has reported.
And what about Windows 11 22H2? Does the change works with Insider Dev? Does Windows Insider Dev fails since version 23606? And does someone has information about canary?

Greetings
Markus

**Comment by slnz00** [comment]
@MScholtes

There are two symbols associated with this GUID: `IID_IVirtualDesktopManagerInternal` and `IID_IVirtualDesktopManagerInternal2`. The latter was introduced around `22H2 22621.2215`, while the former stopped working at that time. @willuhn reported the current GUID stored under the older symbol (`IID_IVirtualDesktopManagerInternal`). It might also work, I haven't tested it.

**Comment by MScholtes** [comment]
OK, I uploaded a test version, which includes the "53F5CA0B-158F-4124-900C-057158060B27" change.

It is called **VirtualDesktop11-3085.cs** and **VirtualDesktop11-3085.exe**. It would be very helpful if soneone with an Insider version of Windows would test this too (please include build numbers in replies).

Greetings

Markus

**Comment by iamsteelone** [comment]
Good Morning

I pulled the latest update this morning but I'm still getting the errors (Win Ver  23H2 22631.3085, running VirtualDesktop11-3085.exe)
![image](https://github.com/MScholtes/VirtualDesktop/assets/29373666/be261b02-93c8-40f2-a328-8750aea5e536)
![image](https://github.com/MScholtes/VirtualDesktop/assets/29373666/128fb548-0b99-4564-b864-3c09debcee5d)

**Comment by MScholtes** [comment]
Hello @iamsteelone,

are you sure you are running Windows 11 23H2 22631.3085? In all my tests VirtualDesktop11-3085.exe worked.

What commands are you executing? Does "VirtualDesktop11-3085.exe LIST" work, what is the current situation?

Greetings Markus

**Comment by iamsteelone** [comment]
Turned out a good old fashioned “turning it off and on again” was needed.  All sorted now

**Comment by MScholtes** [comment]
Hello,

I released new versions today fixing the February monthly security update.
I'm sorry I have got no feedback for Windows 11 22H2. Don't know whether it works or not.

Greetings

Markus

**Comment by sharpsteelsoftware** [comment]
PS C:\Users\jose> M:\software\VirtualDesktop-master\VirtualDesktop.exe "-Switch:Desktop 2"

Unhandled Exception: System.TypeInitializationException: The type initializer for 'VirtualDesktop.DesktopManager' threw an exception. ---> System.InvalidCastException: Specified cast is not valid.
   at VirtualDesktop.IServiceProvider10.QueryService(Guid& service, Guid& riid)
   at VirtualDesktop.DesktopManager..cctor()
   --- End of inner exception stack trace ---
   at VirtualDesktop.Desktop.SearchDesktop(String partialName)
   at VDeskTool.Program.Main(String[] args)

This is failing on Version	10.0.22631 Build 22631 Windows 11

**Comment by MScholtes** [comment]
Issues solved (maybe new issues coming with 24H2)
