### ISSUE TITLE
Guidance Required

### ISSUE THREAD

**Issue by Taster-git** [MScholtes/VirtualDesktop#79]
Hi all,
I am confused because **I failed to find** VirtualDesktop solution file for **Win11 21H2 22000.2538**
Please guide.

Also, guide me if I am wrong
virtualdesktop.cs is for **Win10 22H2 19045.4046**
virtualdesktop11-22h2.cs is for **Win11 22H2 22621.3155**
virtualdesktop11.cs is for **Win11 23H2 22631.3155**

I am thankful that you answered me as I am at a beginner level.

**Comment by MScholtes** [comment]
Hello @Taster-git,

**Windows 11 21H2** is out of support from **Microsoft** for four months now. I join Microsoft in this.

The other allocations are correct, Win11 22H2 is just a guess, I have no feedback on this.

Greetings

Markus

**Comment by LaponiaAmo** [comment]
Thanks for VirtualDesktop. I use it daily in my AutoHotkey script and it makes jumping around between my nine virtual desktops butter smooth. I salute you.

Along the lines of the question by @Taster-git, is the "VirtualDesktop.exe" that has no number appended meant to be used on Windows 10 only? Maybe append a number to it as well...?

Thanks again for developing this project!

**Comment by Taster-git** [comment]
Thanks for your quick reply. @MScholtes 
Please further info as it is partially related to the Virtual desktop.
As you mentioned in the read me page **virtualdesktop11-22h2.cs** for **Windows 11 22H2 release 2215 and newer**.
My question is where we can know the release 2215 or something different according to the OS version?
@NyaMisty @Zoynels 

Thanks.

**Comment by Taster-git** [comment]
> Thanks for VirtualDesktop. I use it daily in my AutoHotkey script and it makes jumping around between my nine virtual desktops butter smooth. I salute you.
> 
> Along the lines of the question by @Taster-git, is the "VirtualDesktop.exe" that has no number appended meant to be used on Windows 10 only? Maybe append a number to it as well...?
> 
> Thanks again for developing this project!

Yes. It will be used only for Windows 10. I have verified.

**Comment by MScholtes** [comment]
Hello,

@LaponiaAmo: as stated on the readme page,  virtualdesktop.exe is for Windows 10,

@Taster-git: My preferred way to get the version is to start **WinVer.exe**. The build number displayed in **Powershell** might be wrong as it's the version of **Powershell**.

Greetings

Markus

**Comment by Taster-git** [comment]
Thanks for your reply.

I **found** that **virtualdesktop11.exe** works **fine** for me for **Win11 22H2 22621.3155** instead of **virtualdesktop11-22h2.cs**.
@MScholtes 

Thanks.

**Comment by MScholtes** [comment]
Hello @Taster-git,

thank you for your feedback, I suspected this, but had no other response for Win 11 22H2 until now.

I will delete the now needless files soon.

Grettings

Markus

**Comment by nevillekatila** [comment]
Hi @MScholtes I can confirm that virtualdesktop11.exe works for Win 11 22H2 2261.3447 but virtualdesktop11-22h2.exe results in an error (that too a pretty explicit one with a messagebox, wondering if I can disable that messagebox from appearing when a wrong exe is used).

**Comment by MScholtes** [comment]
Hello @nevillekatila,

sorry, I forgot to delete the unnecessary version Virtualdesktop11-22h2, caught up today. Every supported **Windows 11** should work with **VirtualDesktop11.exe**.

Greetings

Markus

**Comment by nevillekatila** [comment]
@MScholtes Thanks for that update.

**Comment by MScholtes** [comment]
New version of virtualdesktop without 11 22H2-version.
