### ISSUE TITLE
WinExist in another Virtual Desktop

### ISSUE THREAD

**Issue by jdmarch** [MScholtes/VirtualDesktop#80]
It would be great to have a hotkey which checks whether a specific app (window) is open in any Virtual Desktop, and if it is, activates it in its already-existing desktop. If it does not yet exist, I would open it in the current desktop, but YMMV. Thanks!

**Comment by MScholtes** [comment]
Hello @jdmarch,

not sure if you mean my repository. _Virtualdesktop_ is a pure command line program that does not know hotkeys.

You can accomplish what you want with the following commands at a _cmd.exe_ prompt (assuming the app you are searching is **notepad**):

```cmd
virtualdesktop.exe /GetDesktopFromWindow:notepad
if %ERRORLEVEL% GEQ 0 ( virtualdesktop.exe /Switch:%ERRORLEVEL% ) else ( start notepad )
```

Greetings

Markus

**Comment by jdmarch** [comment]
My apologies, Markus. Indeed, not the repo I intended (that was https://github.com/FuPeiJiang/VD.ahk). But your response is on point nonetheless, thank you!

**Comment by jdmarch** [comment]
(I see what happened -- I clicked on the "create an issue" link in a comment of *yours* which had been pasted into the VD.ahk repo home page.)
