### ISSUE TITLE
/RemoveAll does not respect /Quiet flag 

### ISSUE THREAD

**Issue by R2RT** [MScholtes/VirtualDesktop#81]
Current release:

```
> VirtualDesktop.exe /?
VirtualDesktop.exe                              Markus Scholtes, 2024, v1.17
```

Without `/Quiet`:

```
>VirtualDesktop.exe /RemoveAll /New
Removing all virtual desktops but visible
Creating virtual desktop number 1
```

With `/Quiet`:

```
>VirtualDesktop.exe /Quiet /RemoveAll /New
Removing all virtual desktops but visible
```

Btw, is there any better way to ensure that exactly two desktops exist with single `VirtualDesktop` executable call?

PS. Thanks for the project :)

**Comment by MScholtes** [comment]
Hello @R2RT,

released new version 1.18 of VirtualDesktop today that fixes this issue.

Greetings

Markus
