### ISSUE TITLE
AutoHotkey Example Script if anyone is interested

### ISSUE THREAD

**Issue by afkjm** [MScholtes/VirtualDesktop#82]
Hey there, nice project. 

I just published an AutoHotkey script which solves some nuanced issues when attempting to use Alt + 1, Alt + 2 (XFCE-style) based virtual desktop switching hotkeys. 

You'll find it here: https://github.com/afkjm/VirtualDesktop-AHK/

Have a good one.

**Comment by MScholtes** [comment]
Thank you for your information
