### ISSUE TITLE
Restart virtualdesktop if it's crashed?

### ISSUE THREAD

**Issue by wkearney99** [MScholtes/VirtualDesktop#89]
I've had an periodic problem with the virtual desktop subsystem seeming to crash now and then.  This is not an issue with this package, but I'd wonder, short of doing a reboot, is there a way to 'restart' the virtual desktop subsystem?  I ask this because when I happens I often have long-running tasks orphaned in one of the other virtual desktops that I'd like to reconnect.  They're "still running" but their window is inaccessible.

Any clues/suggestions?

**Comment by wkearney99** [comment]
Update, sort of fixed it by killing the ShellExperienceHost.exe process.

**Comment by MScholtes** [comment]
Hello @wkearney99,
You will understand that I can only provide support for my tool.
Apart from that, I have no idea (how do you make Virtual Desktops crash?)

Greetings
Markus

**Comment by wkearney99** [comment]
If you have a lot of windows and tabs open in chrome and you start pushing the limits of RAM things can get 'strange'.  It doesn't happen often but when it goes it's a hassle, as you're stuck on "one" of the virtual desktops but can't get "over" to the others.  Which means when you force a reboot you're faced with all those windows/tabs coming back to the wrong virtual desktops.

Yes, it would be "better" to not have 100+ windows open.  My brain doesn't work that way, Lord knows I've tried...
