### ISSUE TITLE
Feature Add a command line option to pin the active window

### ISSUE THREAD

**Issue by clemensschlipfinger** [MScholtes/VirtualDesktop#91]
Hello @MScholtes ,
thank you for creating this great command line tool, i use it every day!
I control it using keybindings to navigate between my desktops which works very well.
However I want to be able to easily pin windows to all desktops with a keybinding and of course this does not work if i have to specifiy their name. So i added option `PinActiveWindow` and `UnPinActiveWindow`.

Maybe you want to incorporate this feature too. Feel free to grab the code from my repo  [https://github.com/clemensschlipfinger/VirtualDesktop](VirtualDesktop).

All the best!

**Comment by MScholtes** [comment]
Hello @clemensschlipfinger,

seems like an good idea - and easy to implement. I will iclude this in the next version.

Thanks and greetings

Markus
